### ISSUE TITLE
sandbox: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#62]
### What?
The browser console shows:

```
[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoaderModule.php(830): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(656): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#9 [internal function]: ResourceLoader->{closure}(string)
#10 /../w/includes/resourceloader/ResourceLoader.php(668): array_map(Closure, array)
#11 /../w/includes/resourceloader/ResourceLoader.php(749): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#12 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#13 {main}

[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoader.php(1068): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(772): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#9 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#10 {main}

Problematic modules: {"startup":"error"}
[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoaderModule.php(830): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(656): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#9 [internal function]: ResourceLoader->{closure}(string)
#10 /../w/includes/resourceloader/ResourceLoader.php(668): array_map(Closure, array)
#11 /../w/includes/resourceloader/ResourceLoader.php(749): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#12 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#13 {main}

[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoader.php(1068): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(772): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#9 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#10 {main}

Problematic modules: {"startup":"error"}[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoaderModule.php(830): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(656): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#9 [internal function]: ResourceLoader->{closure}(string)
#10 /../w/includes/resourceloader/ResourceLoader.php(668): array_map(Closure, array)
#11 /../w/includes/resourceloader/ResourceLoader.php(749): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#12 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#13 {main}

[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoader.php(1068): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(772): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#9 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#10 {main}

Problematic modules: {"startup":"error"}[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoaderModule.php(830): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(656): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#9 [internal function]: ResourceLoader->{closure}(string)
#10 /../w/includes/resourceloader/ResourceLoader.php(668): array_map(Closure, array)
#11 /../w/includes/resourceloader/ResourceLoader.php(749): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#12 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#13 {main}

[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoader.php(1068): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(772): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#9 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#10 {main}

Problematic modules: {"startup":"error"}
[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoaderModule.php(830): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(656): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#9 [internal function]: ResourceLoader->{closure}(string)
#10 /../w/includes/resourceloader/ResourceLoader.php(668): array_map(Closure, array)
#11 /../w/includes/resourceloader/ResourceLoader.php(749): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#12 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#13 {main}

[ea23a1343f755ca0261db527] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /../w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /../w/extensions/VisualEditor/includes/VisualEditorHooks.php(918): GlobalVarConfig->get(string)
#1 /../w/includes/Hooks.php(174): VisualEditorHooks::onResourceLoaderGetConfigVars(array, string)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(127): Hooks::run(string, array)
#4 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getConfigSettings(ResourceLoaderContext)
#5 /../w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#6 /../w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#7 /../w/includes/resourceloader/ResourceLoader.php(1068): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#8 /../w/includes/resourceloader/ResourceLoader.php(772): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#9 /../w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#10 {main}

Problematic modules: {"startup":"error"}
```

### Caused by 

I'm guessing this relates to MediaWiki | 1.33.0-rc.0 (c733c85) 7 juin 2019 à 19:29.

**Comment by mwjames** [comment]
The error prevents any JS to be loaded or executed including the search box, elasticsearch replication check etc..

**Comment by mwjames** [comment]
The error not only appears with VE but also with `MobileFrontend`:

```
[1d0cb3e99a5350f2cb1bff60] /w/load.php?lang=fr&modules=startup&only=scripts&skin=vector   ConfigException from line 53 of /var/www/html/sbxsmw/w/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'EnableBlockNoticeStats'
Backtrace:
#0 /var/www/html/sbxsmw/w/extensions/MobileFrontend/includes/MobileFrontend.hooks.php(428): GlobalVarConfig->get(string)
#1 /var/www/html/sbxsmw/w/extensions/MobileFrontend/includes/modules/ResourceLoaderFileModuleWithMFConfig.php(16): MobileFrontendHooks::getResourceLoaderMFConfigVars()
#2 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderModule.php(727): MobileFrontend\ResourceLoaderModules\ResourceLoaderFileModuleWithMFConfig->getScript(ResourceLoaderContext)
#3 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#4 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderModule.php(830): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#5 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderStartUpModule.php(255): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#6 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderStartUpModule.php(438): ResourceLoaderStartUpModule->getModuleRegistrations(ResourceLoaderContext)
#7 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderModule.php(727): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#8 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderModule.php(694): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#9 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoaderModule.php(830): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#10 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoader.php(656): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#11 [internal function]: ResourceLoader->{closure}(string)
#12 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoader.php(668): array_map(Closure, array)
#13 /var/www/html/sbxsmw/w/includes/resourceloader/ResourceLoader.php(749): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#14 /var/www/html/sbxsmw/w/load.php(46): ResourceLoader->respond(ResourceLoaderContext)
#15 {main}
```

**Comment by kghbln** [comment]
@mwjames Sadly I do not get notifications on new issues, whatever setting I set my GitHub account to. I only saw this via my notifications tab.

Anyways I saw this issue too after the upgrade, reported the issue as [task T225354](https://phabricator.wikimedia.org/T225354) and disabled my beloved VisualEdior.

**Comment by kghbln** [comment]
Fixed for [VisualEditor](https://phabricator.wikimedia.org/T225354) but still broken for [MobileFrontend.](https://phabricator.wikimedia.org/T225359)

**Comment by kghbln** [comment]
Now also fixed for MF.
