### ISSUE TITLE
GraphViz::getUser / PermissionManager::overrideUserRightsForTesting can not be called outside of tests

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#75]
Trying to access https://sandbox.semantic-mediawiki.org/wiki/Hello_world throws a:

```
[ed42bd9255024c3d73f3d76e] /wiki/Hello_world Exception from line 1614 of /var/www/html/sbxsmw/w/includes/Permissions/PermissionManager.php: MediaWiki\Permissions\PermissionManager::overrideUserRightsForTesting can not be called outside of tests

Backtrace:

#0 /var/www/html/sbxsmw/w/includes/user/User.php(266): MediaWiki\Permissions\PermissionManager->overrideUserRightsForTesting(User, array)
#1 /var/www/html/sbxsmw/w/extensions/GraphViz/includes/GraphViz.php(466): User->__set(string, array)
#2 /var/www/html/sbxsmw/w/extensions/GraphViz/includes/GraphViz.php(641): MediaWiki\Extension\GraphViz\GraphViz::getUser()
#3 /var/www/html/sbxsmw/w/extensions/GraphViz/includes/GraphViz.php(444): MediaWiki\Extension\GraphViz\GraphViz::render(string, array, Parser, PPFrame_Hash)
#4 /var/www/html/sbxsmw/w/includes/parser/Parser.php(4293): MediaWiki\Extension\GraphViz\GraphViz::graphvizParserHook(string, array, Parser, PPFrame_Hash)
#5 /var/www/html/sbxsmw/w/includes/parser/PPFrame_Hash.php(328): Parser->extensionSubstitution(array, PPFrame_Hash)
#6 /var/www/html/sbxsmw/w/includes/parser/Parser.php(3330): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#7 /var/www/html/sbxsmw/w/includes/parser/Parser.php(1489): Parser->replaceVariables(string)
#8 /var/www/html/sbxsmw/w/includes/parser/Parser.php(593): Parser->internalParse(string)
#9 /var/www/html/sbxsmw/w/includes/content/WikitextContent.php(368): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#10 /var/www/html/sbxsmw/w/includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#11 /var/www/html/sbxsmw/w/includes/Revision/RenderedRevision.php(267): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#12 /var/www/html/sbxsmw/w/includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#13 /var/www/html/sbxsmw/w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#14 /var/www/html/sbxsmw/w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#15 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#16 /var/www/html/sbxsmw/w/includes/Revision/RenderedRevision.php(198): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#17 /var/www/html/sbxsmw/w/includes/poolcounter/PoolWorkArticleView.php(196): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#18 /var/www/html/sbxsmw/w/includes/poolcounter/PoolCounterWork.php(125): PoolWorkArticleView->doWork()
#19 /var/www/html/sbxsmw/w/includes/page/Article.php(791): PoolCounterWork->execute()
#20 /var/www/html/sbxsmw/w/includes/actions/ViewAction.php(63): Article->view()
#21 /var/www/html/sbxsmw/w/includes/MediaWiki.php(511): ViewAction->show()
#22 /var/www/html/sbxsmw/w/includes/MediaWiki.php(302): MediaWiki->performAction(Article, Title)
#23 /var/www/html/sbxsmw/w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#24 /var/www/html/sbxsmw/w/includes/MediaWiki.php(527): MediaWiki->main()
#25 /var/www/html/sbxsmw/w/index.php(44): MediaWiki->run()
#26 {main}
```

**Comment by kghbln** [comment]
Already reported as [T238990](https://phabricator.wikimedia.org/T238990). I thought to have already killed this extension from sandbox. Done so now. There is nothing we can do here and I do not expect solutions since the extension was basically abandoned. Thus closing.
