### ISSUE TITLE
Class 'MediaWiki\Extensions\Lockdown\UserGroupMembership' not found

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#76]
Just encountered an error during `&action=purge`.

```
[0cdb9a4b5e128d2b419bc5a3] /w/index.php?title=smw/schema:Group:User-defined_properties&action=purge Error from line 48 of /var/www/html/sbxsmw/w/extensions/Lockdown/src/Hooks.php: Class 'MediaWiki\Extensions\Lockdown\UserGroupMembership' not found

Backtrace:

#0 /var/www/html/sbxsmw/w/extensions/Lockdown/src/Hooks.php(180): MediaWiki\Extensions\Lockdown\Hooks::getGroupLinks(array)
#1 /var/www/html/sbxsmw/w/includes/Hooks.php(174): MediaWiki\Extensions\Lockdown\Hooks::onMediawikiPerformAction(OutputPage, Article, Title, User, WebRequest, MediaWiki)
#2 /var/www/html/sbxsmw/w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /var/www/html/sbxsmw/w/includes/MediaWiki.php(483): Hooks::run(string, array)
#4 /var/www/html/sbxsmw/w/includes/MediaWiki.php(302): MediaWiki->performAction(Article, Title)
#5 /var/www/html/sbxsmw/w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#6 /var/www/html/sbxsmw/w/includes/MediaWiki.php(527): MediaWiki->main()
#7 /var/www/html/sbxsmw/w/index.php(44): MediaWiki->run()
#8 {main}
```

**Comment by kghbln** [comment]
@mwjames Thanks for reporting. Luckily already fixed upstream in November 2019 with [0aac342](https://github.com/wikimedia/mediawiki-extensions-Lockdown/commit/0aac342ad4fe02b6561f974eae7e872eaa0d2aee). Thus it was a matter of just updating the code on the server for the branch. En passant I was able to fix a tiny additional issue myself at the same time.
