### ISSUE TITLE
 InvalidArgumentException from line 238 of "ObjectFactory.php": Provided specification is not an array.

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#77]
Trying to access [0] is followed by:

```
[c8ea62749dc97399af2bced0] /wiki/Sp%C3%A9cial:Pages_sp%C3%A9ciales InvalidArgumentException from line 238 of /var/www/html/sbxsmw/w/vendor/wikimedia/object-factory/src/ObjectFactory.php: Provided specification is not an array.

Backtrace:

#0 /var/www/html/sbxsmw/w/vendor/wikimedia/object-factory/src/ObjectFactory.php(131): Wikimedia\ObjectFactory::validateSpec(string, array)
#1 /var/www/html/sbxsmw/w/vendor/wikimedia/object-factory/src/ObjectFactory.php(102): Wikimedia\ObjectFactory::getObjectFromSpec(string, array)
#2 /var/www/html/sbxsmw/w/includes/specialpage/SpecialPageFactory.php(447): Wikimedia\ObjectFactory->createObject(string, array)
#3 /var/www/html/sbxsmw/w/includes/specialpage/SpecialPageFactory.php(478): MediaWiki\Special\SpecialPageFactory->getPage(string)
#4 /var/www/html/sbxsmw/w/includes/specials/SpecialSpecialpages.php(56): MediaWiki\Special\SpecialPageFactory->getUsablePages(User)
#5 /var/www/html/sbxsmw/w/includes/specials/SpecialSpecialpages.php(44): SpecialSpecialpages->getPageGroups()
#6 /var/www/html/sbxsmw/w/includes/specialpage/SpecialPage.php(575): SpecialSpecialpages->execute(NULL)
#7 /var/www/html/sbxsmw/w/includes/specialpage/SpecialPageFactory.php(611): SpecialPage->run(NULL)
#8 /var/www/html/sbxsmw/w/includes/MediaWiki.php(296): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#9 /var/www/html/sbxsmw/w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#10 /var/www/html/sbxsmw/w/includes/MediaWiki.php(527): MediaWiki->main()
#11 /var/www/html/sbxsmw/w/index.php(44): MediaWiki->run()
#12 {main}
```

[0] https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Pages_sp%C3%A9ciales

**Comment by kghbln** [comment]
Reported upstream with [T250582.](https://phabricator.wikimedia.org/T250582)

**Comment by kghbln** [comment]
Caused by Maps and reported over there: https://github.com/JeroenDeDauw/Maps/issues/616

**Comment by kghbln** [comment]
Fix deployed. Thanks!
